### ISSUE TITLE
Is it possible to clone an object without reallocating memory?

### ISSUE THREAD

**Issue by dzackgarza** [renkun-ken/sharedata#1]
I'm loading a large .RDA file into one R session, which I am trying to reference in other sessions. To do so, I'm just using the code from http://renkun.me/sharedata/

![image](https://cloud.githubusercontent.com/assets/1149853/14369010/7c9cc4b2-fcd6-11e5-9e0b-7c69ded4c6c0.png)

However, each new "clone_object" call seems to allocate a significant chunk of new memory. Is there any way to get something like a reference/pointer to, for example, the "data" object in the above example?

**Comment by renkun-ken** [comment]
I don't think it is possible because an R object can not be shared in two R sessions without copying unless you keep operating the pointer in pure C/C++.
